javac CheckAgent1.java
javac CheckAgent2.java
javac CheckAgent3.java
javac CheckAgent4.java
javac CheckAgent5.java
javac CheckAgent6.java
javac CheckAgent7.java
javac CheckAgent8.java
javac CheckAgent9.java
javac CheckAgent10.java
javac CheckAgent11.java
javac CheckAgent12.java
javac CheckAgent13.java
javac CheckAgent14.java
javac CheckAgent15.java
javac CheckAgent16.java